
$date = get-date 

$date | Get-Member


   TypeName: System.DateTime

Name                 MemberType     Definition                                                                                                                                                                                                                                    
----                 ----------     ----------                                                                                                                                                                                                                                    
Add                  Method         datetime Add(timespan value)                                                                                                                                                                                                                  
AddDays              Method         datetime AddDays(double value)                                                                                                                                                                                                                
AddHours             Method         datetime AddHours(double value)                                                                                                                                                                                                               
AddMilliseconds      Method         datetime AddMilliseconds(double value)                                                                                                                                                                                                        
AddMinutes           Method         datetime AddMinutes(double value)                                                                                                                                                                                                             
AddMonths            Method         datetime AddMonths(int months)                                                                                                                                                                                                                
AddSeconds           Method         datetime AddSeconds(double value)                                                                                                                                                                                                             
AddTicks             Method         datetime AddTicks(long value)                                                                                                                                                                                                                 
AddYears             Method         datetime AddYears(int value)                                                                                                                                                                                                                  
CompareTo            Method         int CompareTo(System.Object value), int CompareTo(datetime value), int IComparable.CompareTo(System.Object obj), int IComparable[datetime].CompareTo(datetime other)                                                                          
Equals               Method         bool Equals(System.Object value), bool Equals(datetime value), bool IEquatable[datetime].Equals(datetime other)                                                                                                                               
GetDateTimeFormats   Method         string[] GetDateTimeFormats(), string[] GetDateTimeFormats(System.IFormatProvider provider), string[] GetDateTimeFormats(char format), string[] GetDateTimeFormats(char format, System.IFormatProvider provider)                              
GetHashCode          Method         int GetHashCode()                                                                                                                                                                                                                             
GetObjectData        Method         void ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)                                                                                                  
GetType              Method         type GetType()                                                                                                                                                                                                                                
GetTypeCode          Method         System.TypeCode GetTypeCode(), System.TypeCode IConvertible.GetTypeCode()                                                                                                                                                                     
IsDaylightSavingTime Method         bool IsDaylightSavingTime()                                                                                                                                                                                                                   
Subtract             Method         timespan Subtract(datetime value), datetime Subtract(timespan value)                                                                                                                                                                          
ToBinary             Method         long ToBinary()                                                                                                                                                                                                                               
ToBoolean            Method         bool IConvertible.ToBoolean(System.IFormatProvider provider)                                                                                                                                                                                  
ToByte               Method         byte IConvertible.ToByte(System.IFormatProvider provider)                                                                                                                                                                                     
ToChar               Method         char IConvertible.ToChar(System.IFormatProvider provider)                                                                                                                                                                                     
ToDateTime           Method         datetime IConvertible.ToDateTime(System.IFormatProvider provider)                                                                                                                                                                             
ToDecimal            Method         decimal IConvertible.ToDecimal(System.IFormatProvider provider)                                                                                                                                                                               
ToDouble             Method         double IConvertible.ToDouble(System.IFormatProvider provider)                                                                                                                                                                                 
ToFileTime           Method         long ToFileTime()                                                                                                                                                                                                                             
ToFileTimeUtc        Method         long ToFileTimeUtc()                                                                                                                                                                                                                          
ToInt16              Method         int16 IConvertible.ToInt16(System.IFormatProvider provider)                                                                                                                                                                                   
ToInt32              Method         int IConvertible.ToInt32(System.IFormatProvider provider)                                                                                                                                                                                     
ToInt64              Method         long IConvertible.ToInt64(System.IFormatProvider provider)                                                                                                                                                                                    
ToLocalTime          Method         datetime ToLocalTime()                                                                                                                                                                                                                        
ToLongDateString     Method         string ToLongDateString()                                                                                                                                                                                                                     
ToLongTimeString     Method         string ToLongTimeString()                                                                                                                                                                                                                     
ToOADate             Method         double ToOADate()                                                                                                                                                                                                                             
ToSByte              Method         sbyte IConvertible.ToSByte(System.IFormatProvider provider)                                                                                                                                                                                   
ToShortDateString    Method         string ToShortDateString()                                                                                                                                                                                                                    
ToShortTimeString    Method         string ToShortTimeString()                                                                                                                                                                                                                    
ToSingle             Method         float IConvertible.ToSingle(System.IFormatProvider provider)                                                                                                                                                                                  
ToString             Method         string ToString(), string ToString(string format), string ToString(System.IFormatProvider provider), string ToString(string format, System.IFormatProvider provider), string IFormattable.ToString(string format, System.IFormatProvider fo...
ToType               Method         System.Object IConvertible.ToType(type conversionType, System.IFormatProvider provider)                                                                                                                                                       
ToUInt16             Method         uint16 IConvertible.ToUInt16(System.IFormatProvider provider)                                                                                                                                                                                 
ToUInt32             Method         uint32 IConvertible.ToUInt32(System.IFormatProvider provider)                                                                                                                                                                                 
ToUInt64             Method         uint64 IConvertible.ToUInt64(System.IFormatProvider provider)                                                                                                                                                                                 
ToUniversalTime      Method         datetime ToUniversalTime()                                                                                                                                                                                                                    
DisplayHint          NoteProperty   DisplayHintType DisplayHint=DateTime                                                                                                                                                                                                          
Date                 Property       datetime Date {get;}                                                                                                                                                                                                                          
Day                  Property       int Day {get;}                                                                                                                                                                                                                                
DayOfWeek            Property       System.DayOfWeek DayOfWeek {get;}                                                                                                                                                                                                             
DayOfYear            Property       int DayOfYear {get;}                                                                                                                                                                                                                          
Hour                 Property       int Hour {get;}                                                                                                                                                                                                                               
Kind                 Property       System.DateTimeKind Kind {get;}                                                                                                                                                                                                               
Millisecond          Property       int Millisecond {get;}                                                                                                                                                                                                                        
Minute               Property       int Minute {get;}                                                                                                                                                                                                                             
Month                Property       int Month {get;}                                                                                                                                                                                                                              
Second               Property       int Second {get;}                                                                                                                                                                                                                             
Ticks                Property       long Ticks {get;}                                                                                                                                                                                                                             
TimeOfDay            Property       timespan TimeOfDay {get;}                                                                                                                                                                                                                     
Year                 Property       int Year {get;}                                                                                                                                                                                                                               
DateTime             ScriptProperty System.Object DateTime {get=if ((& { Set-StrictMode -Version 1; $this.DisplayHint }) -ieq  "Date")...
